// Mocks generated by Mockito 5.4.6 from annotations
// in agriapp/test/veiculo_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:agriapp/features/veiculo/data/datasources/local/veiculo_local_datasource.dart'
    as _i5;
import 'package:agriapp/features/veiculo/data/datasources/remote/veiculo_remote_datasource.dart'
    as _i2;
import 'package:agriapp/features/veiculo/data/models/veiculo_model.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [VeiculoRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockVeiculoRemoteDataSource extends _i1.Mock
    implements _i2.VeiculoRemoteDataSource {
  MockVeiculoRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.VeiculoModel>> getVeiculos() =>
      (super.noSuchMethod(
            Invocation.method(#getVeiculos, []),
            returnValue: _i3.Future<List<_i4.VeiculoModel>>.value(
              <_i4.VeiculoModel>[],
            ),
          )
          as _i3.Future<List<_i4.VeiculoModel>>);

  @override
  _i3.Future<void> createVeiculo(_i4.VeiculoModel? veiculo) =>
      (super.noSuchMethod(
            Invocation.method(#createVeiculo, [veiculo]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateVeiculo(int? id, _i4.VeiculoModel? veiculo) =>
      (super.noSuchMethod(
            Invocation.method(#updateVeiculo, [id, veiculo]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteVeiculo(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteVeiculo, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [VeiculoLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockVeiculoLocalDataSource extends _i1.Mock
    implements _i5.VeiculoLocalDataSource {
  MockVeiculoLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.VeiculoModel>> getCachedVeiculos() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedVeiculos, []),
            returnValue: _i3.Future<List<_i4.VeiculoModel>>.value(
              <_i4.VeiculoModel>[],
            ),
          )
          as _i3.Future<List<_i4.VeiculoModel>>);

  @override
  _i3.Future<void> cacheVeiculos(List<_i4.VeiculoModel>? veiculos) =>
      (super.noSuchMethod(
            Invocation.method(#cacheVeiculos, [veiculos]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
